name: Deploy on self-hosted runner

on:
  push:
    branches:  
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ACR
        run: |
          echo "${{ secrets.AZURE_PASSWORD }}" | docker login koiauctionwebapp.azurecr.io --username "${{ secrets.AZURE_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t koiauctionwebapp.azurecr.io/auctionkoi-be-server:latest .

      - name: Push Docker image to ACR
        run: |
          docker push koiauctionwebapp.azurecr.io/auctionkoi-be-server:latest

      - name: Run `docker compose`
        run: |
          docker compose up --build -d
